# Generated by Django 4.2.7 on 2025-06-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_in_stock_remove_product_old_price_and_more"),
        ("cart", "0002_alter_cartitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_format",
        ),
    ]
