# Generated by Django 4.2.7 on 2025-06-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Paiement à la livraison"),
                    ("mobile_money", "Mobile Money"),
                    ("bank_transfer", "Virement bancaire"),
                ],
                default="cash_on_delivery",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(default="Cameroun", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_postal_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
