# Generated by Django 4.2.7 on 2025-06-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_method_order_shipping_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="billing_postal_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_postal_code",
        ),
    ]
