# Generated by Django 4.2.7 on 2025-06-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_old_price_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
        migrations.CreateModel(
            name="ProductFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("250ml", "250ml"),
                            ("500ml", "500ml"),
                            ("1l", "1 Litre"),
                            ("1.5l", "1.5 Litre"),
                            ("2l", "2 Litres"),
                            ("pack_4x250ml", "Pack 4x250ml"),
                            ("pack_6x250ml", "Pack 6x250ml"),
                            ("pack_12x250ml", "Pack 12x250ml"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("in_stock", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formats",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Format de produit",
                "verbose_name_plural": "Formats de produits",
                "ordering": ["price"],
                "unique_together": {("product", "size")},
            },
        ),
    ]
